-- DROP table if exists  user ;
-- create table user (
--   id bigint  unsigned AUTO_INCREMENT,
--   username varchar(40),
--   name varchar (20),
--   age int,
--   balance decimal (3),
--   primary  key (id));

DROP Table user if exists ;
create table user (
  id bigint  generated by default as identity ,
  username varchar(40),
  name varchar (20),
  age int,
  balance decimal (3),
  primary  key (id));